# Data Inspection & Overview

* `pd.read_csv(...)` — Loads a CSV file into a 2D tabular DataFrame.
* `df.head()` — Shows the first 5 rows (useful for a quick structure preview).
* `df.tail()` — Shows the last 5 rows.
* `df.info()` — Displays column names, non-null counts, and data types (`dtypes`).
* `df.describe()` — Computes summary statistics (mean, std, min, quartiles, max) for numeric columns.

In [339]:
import pandas as pd
#csv stands for comma seperated values, pandas are typically used with csv files or excel spreedsheets etc

# Key Features:
# - Label-based indexing
# - Column-wise and row-wise operations
# - Support for mixed data types
# - Fast, vectorized operations (built on NumPy)

# df (DataFrame) is a 2D labeled data structure like a spreadsheet table with rows and columns
# df = pd.read_csv("Notes/Panda/orders.csv") # relative path from working directory
# 'r' treats backslashes as raw text to prevent unicode escape errors
df = pd.read_csv(r"C:\Users\zaman\Desktop\ChE 208\Python\Notes\Panda\orders.csv")

In [340]:
print(df)

    OrderID      CustomerName                Product     Category  Quantity  \
0      1001        John Smith                 Laptop  Electronics         1
1      1002         Sarah Lee             Headphones  Electronics         2
2      1003          Ali Khan           Office Chair    Furniture         1
3      1004        Alice Wong              Desk Lamp    Furniture         3
4      1005     Carlos Mendez               Keyboard  Electronics         2
5      1006      Nora Ibrahim               Notebook   Stationery         5
6      1007       Emily Davis          Standing Desk    Furniture         1
7      1008        James Park                Monitor  Electronics         2
8      1009       Maria Rossi                    Pen   Stationery        10
9      1010  Takeshi Nakamura                  Mouse  Electronics         1
10     1011     Sophie Martin                 Webcam  Electronics         1
11     1012         Raj Patel           File Cabinet    Furniture         2
12     1013       Emma Wilson                Stapler   Stationery         3
13     1014   Diego Rodriguez              USB Drive  Electronics         5
14     1015         Lisa Chen              Bookshelf    Furniture         1
15     1016      Ahmed Hassan          Printer Paper   Stationery        20
16     1017     Anna Kowalski         Wireless Mouse  Electronics         2
17     1018     Michael Brown         Desk Organizer    Furniture         1
18     1019       Yuki Tanaka             Calculator  Electronics         1
19     1020   Fatima Al-Zahra             Whiteboard    Furniture         1
20     1021    David Thompson           Highlighters   Stationery         8
21     1022    Isabella Silva      Bluetooth Speaker  Electronics         1
22     1023    Oliver Schmidt           Office Plant    Furniture         2
23     1024        Zara Ahmed           Sticky Notes   Stationery        15
24     1025    Lucas Anderson           Tablet Stand  Electronics         1
25     1026      Chloe Dubois         Paper Shredder  Electronics         1
26     1027     Miguel Torres         Desk Chair Mat    Furniture         1
27     1028       Nina Petrov           Binder Clips   Stationery        12
28     1029      Seo-yeon Kim      Wireless Keyboard  Electronics         1
29     1030   Giuseppe Romano          Desk Calendar    Furniture         1
30     1031      Amira Hassan                USB Hub  Electronics         1
31     1032     Thomas Müller       Document Scanner  Electronics         1
32     1033   Sofia Rodriguez  Desk Drawer Organizer    Furniture         1
33     1034      Alex Johnson            Index Cards   Stationery       100
34     1035     Yuki Yamamoto          Monitor Stand  Electronics         1
35     1036     Emma Thompson     Desk Lamp with USB    Furniture         1
36     1037     Carlos Santos       Wireless Earbuds  Electronics         1
37     1038    Leila Mansouri               Desk Pad    Furniture         1
38     1039        Daniel Kim            Power Strip  Electronics         2
39     1040      Anna Ivanova             Desk Clock    Furniture         1

     Price   OrderDate Shipped       Country
0   1200.0  2024-06-01     Yes           USA
1    150.0  2024-06-03      No        Canada
2    300.0  2024-06-04     Yes           UAE
3     45.0  2024-06-05     Yes     Singapore
4     80.0  2024-06-06      No        Mexico
5      5.0  2024-06-07     Yes           UAE
6    450.0  2024-06-08     Yes            UK
7    220.0  2024-06-09      No   South Korea
8      1.5  2024-06-10     Yes         Italy
9     35.0  2024-06-11     Yes         Japan
10    85.0  2024-06-12     Yes        France
11   180.0  2024-06-13      No         India
12    12.0  2024-06-14     Yes     Australia
13    25.0  2024-06-15     Yes         Spain
14   280.0  2024-06-16      No         China
15     8.0  2024-06-17     Yes         Egypt
16    45.0  2024-06-18     Yes        Poland
17    65.0  2024-06-19      No           USA
18    15.0  2024-06-20     Yes         Japan
19   120.0  2024-06-21     Yes  Saudi Arabia
20     3.5  2024-06-22      No        Canada
21    95.0  2024-06-23     Yes        Brazil
22    35.0  2024-06-24     Yes       Germany
23     4.0  2024-06-25      No      Pakistan
24    28.0  2024-06-26     Yes        Sweden
25    75.0  2024-06-27     Yes        France
26    22.0  2024-06-28      No     Argentina
27     2.5  2024-06-29     Yes        Russia
28   110.0  2024-06-30     Yes   South Korea
29    18.0  2024-07-01      No         Italy
30    32.0  2024-07-02     Yes       Morocco
31   140.0  2024-07-03     Yes       Germany
32    42.0  2024-07-04      No      Colombia
33     0.8  2024-07-05     Yes           USA
34    55.0  2024-07-06     Yes         Japan
35    68.0  2024-07-07      No            UK
36   125.0  2024-07-08     Yes      Portugal
37    28.0  2024-07-09     Yes          Iran
38    18.0  2024-07-10      No   South Korea
39    35.0  2024-07-11     Yes       Ukraine

In [341]:
df.head()        # First 5 rows

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

In [342]:
df.tail()        # Last 5 rows

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [343]:
df.info()        # Column types and non-null values

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       40 non-null     int64
 1   CustomerName  40 non-null     str
 2   Product       40 non-null     str
 3   Category      40 non-null     str
 4   Quantity      40 non-null     int64
 5   Price         40 non-null     float64
 6   OrderDate     40 non-null     str
 7   Shipped       40 non-null     str
 8   Country       40 non-null     str
dtypes: float64(1), int64(2), str(6)
memory usage: 2.9 KB

In [344]:
df.describe()    # Summary stats

           OrderID    Quantity        Price
count    40.000000   40.000000    40.000000
mean   1020.500000    5.450000   106.457500
std      11.690452   15.903475   201.091854
min    1001.000000    1.000000     0.800000
25%    1010.750000    1.000000    18.000000
50%    1020.500000    1.000000    43.500000
75%    1030.250000    2.250000   112.500000
max    1040.000000  100.000000  1200.000000

# Pandas Indexing & Selection Reference

### 1. DataFrame Structure & Metadata
* `df.columns` — Returns an Index object containing all column headers.
* `df.index` — Returns the row index range or labels (`RangeIndex`).

---

### 2. Column Selection
* `df["Country"]` — **Single-column indexing:** Selects one column as a 1D **Series**.
* `df[["Country"]]` — **DataFrame indexing:** Passing a single-element list preserves the 2D **DataFrame** structure.
* `df[["Country", "Product"]]` — **Multi-column indexing:** Extracts multiple columns as a new **DataFrame**.
* `set(df["Country"])` — Extracts unique, unordered column values using Python's `set()`.
* `len(df["Country"])` — Returns the total count of rows/entries in the column.

---

### 3. Row Selection (`iloc`)
* `df.iloc[0]` — Selects a single row by 0-based integer position as a **Series**.
* `list(df.iloc[0])` — Converts row values into a standard Python `list`.
* `df.iloc[[0, 1, 2]]` — Selects multiple specific rows by positional indices as a **DataFrame**.

---

### 4. Element Access (Row & Column)
* `df.iloc[0, 8]` — **Positional access:** Selects scalar at row index `0`, column index `8`.
* `df.loc[0, "Country"]` — **Label-based access:** Selects scalar at row label `0`, column name `"Country"`.

---

### 5. Multi-Row & Multi-Column Slicing
* `df.iloc[[0, 1, 2], [1, 3]]` — Selects specific rows (`0, 1, 2`) and columns (`1, 3`) by **integer position**.
* `df.loc[[0, 1, 2], ["CustomerName", "Category"]]` — Selects specific rows (`0, 1, 2`) and columns (`"CustomerName", "Category"`) by **label**.

In [345]:
print(df.columns)       # Column names
print(df.index)         # Row indices

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='str')
RangeIndex(start=0, stop=40, step=1)

In [346]:
print(df["Country"]) # This will return a series, A 1D labeled array (like a column)
print(set(df["Country"])) # Set only keeps unique unordered elements
print(len(df["Country"])) # Prints the length of the column
print(len(set(df["Country"]))) # Prints the length of the set

0              USA
1           Canada
2              UAE
3        Singapore
4           Mexico
5              UAE
6               UK
7      South Korea
8            Italy
9            Japan
10          France
11           India
12       Australia
13           Spain
14           China
15           Egypt
16          Poland
17             USA
18           Japan
19    Saudi Arabia
20          Canada
21          Brazil
22         Germany
23        Pakistan
24          Sweden
25          France
26       Argentina
27          Russia
28     South Korea
29           Italy
30         Morocco
31         Germany
32        Colombia
33             USA
34           Japan
35              UK
36        Portugal
37            Iran
38     South Korea
39         Ukraine
Name: Country, dtype: str
{'Saudi Arabia', 'USA', 'South Korea', 'UK', 'Germany', 'Ukraine', 'Canada', 'Singapore', 'Egypt', 'Argentina', 'Russia', 'France', 'Morocco', 'Australia', 'Mexico', 'Sweden', 'Brazil', 'India', 'Pakistan', 'Japan', 'Poland', 'Portugal', 'China', 'Colombia', 'Italy', 'Spain', 'UAE', 'Iran'}
40
28

In [347]:
print(df[["Country", "Product"]]) # List-based column selection, passes a list of multiple column labels to [], extracting multiple columns as a DataFrame.
print(df[["Country"]]) # This is not a series, this is still a DataFrame

         Country                Product
0            USA                 Laptop
1         Canada             Headphones
2            UAE           Office Chair
3      Singapore              Desk Lamp
4         Mexico               Keyboard
5            UAE               Notebook
6             UK          Standing Desk
7    South Korea                Monitor
8          Italy                    Pen
9          Japan                  Mouse
10        France                 Webcam
11         India           File Cabinet
12     Australia                Stapler
13         Spain              USB Drive
14         China              Bookshelf
15         Egypt          Printer Paper
16        Poland         Wireless Mouse
17           USA         Desk Organizer
18         Japan             Calculator
19  Saudi Arabia             Whiteboard
20        Canada           Highlighters
21        Brazil      Bluetooth Speaker
22       Germany           Office Plant
23      Pakistan           Sticky Notes
24        Sweden           Tablet Stand
25        France         Paper Shredder
26     Argentina         Desk Chair Mat
27        Russia           Binder Clips
28   South Korea      Wireless Keyboard
29         Italy          Desk Calendar
30       Morocco                USB Hub
31       Germany       Document Scanner
32      Colombia  Desk Drawer Organizer
33           USA            Index Cards
34         Japan          Monitor Stand
35            UK     Desk Lamp with USB
36      Portugal       Wireless Earbuds
37          Iran               Desk Pad
38   South Korea            Power Strip
39       Ukraine             Desk Clock
         Country
0            USA
1         Canada
2            UAE
3      Singapore
4         Mexico
5            UAE
6             UK
7    South Korea
8          Italy
9          Japan
10        France
11         India
12     Australia
13         Spain
14         China
15         Egypt
16        Poland
17           USA
18         Japan
19  Saudi Arabia
20        Canada
21        Brazil
22       Germany
23      Pakistan
24        Sweden
25        France
26     Argentina
27        Russia
28   South Korea
29         Italy
30       Morocco
31       Germany
32      Colombia
33           USA
34         Japan
35            UK
36      Portugal
37          Iran
38   South Korea
39       Ukraine

In [348]:
print(df.iloc[0])        # iloc = integer-location; selects the first row as a Series (0-based positional index)
print(list(df.iloc[0]))  # Converts that row's values into a standard Python list

OrderID                1001
CustomerName     John Smith
Product              Laptop
Category        Electronics
Quantity                  1
Price                1200.0
OrderDate        2024-06-01
Shipped                 Yes
Country                 USA
Name: 0, dtype: object
[np.int64(1001), 'John Smith', 'Laptop', 'Electronics', np.int64(1), np.float64(1200.0), '2024-06-01', 'Yes', 'USA']

In [349]:
print(df.iloc[[0,1,2]]) # List of specific rows

   OrderID CustomerName       Product     Category  Quantity   Price  \
0     1001   John Smith        Laptop  Electronics         1  1200.0
1     1002    Sarah Lee    Headphones  Electronics         2   150.0
2     1003     Ali Khan  Office Chair    Furniture         1   300.0

    OrderDate Shipped Country
0  2024-06-01     Yes     USA
1  2024-06-03      No  Canada
2  2024-06-04     Yes     UAE

In [350]:
print(df.iloc[0, 8])         # Positional access: row index 0, column index 8 (both integer-based)
print(df.loc[0, "Country"])  # Label-based access: row index label 0, column name "Country"

USA
USA

In [351]:
df.iloc[[0, 1, 2], [1, 3]]           # Specific rows and specific columns by integer position
df.loc[[0, 1, 2], ["CustomerName", "Category"]]   # Specific rows and specific columns by label

  CustomerName     Category
0   John Smith  Electronics
1    Sarah Lee  Electronics
2     Ali Khan    Furniture

# Boolean Indexing & Filtering Reference

### 1. Basic Equality & Comparison
* `df[df["Category"] == "Electronics"]` — **Equality filter:** Returns rows where the column matches an exact value.
* `df[df["Quantity"] > 5]` — **Comparison filter:** Returns rows where a numeric column meets a threshold (`>`, `<`, `>=`, `<=`, `!=`).

---

### 2. Multi-Condition Filtering (Bitwise Operators)
* `df[(df["Category"] == "Electronics") & (df["Country"] == "USA")]` — **Logical AND (`&`):** Both conditions must be True. Parentheses `(...)` around each condition are required.
* `df[(df["Category"] == "Electronics") | (df["Country"] == "USA")]` — **Logical OR (`|`):** At least one condition must be True. Parentheses `(...)` around each condition are required.

---

### 3. String Methods (`.str` Accessor)
* `df[df["CustomerName"].str.startswith("A")]` — Filters rows where the text starts with a given substring.
* `df[df["CustomerName"].str.endswith("n")]` — Filters rows where the text ends with a given substring.
* `df[df["CustomerName"].str.contains("text", case=False)]` — Filters rows where the text contains a substring (case-insensitive flag optional).

---

### 4. Membership & Inversion (`.isin()` & `~`)
* `df[df["Country"].isin(["USA", "Sweden", "Brazil"])]` — **Inclusion:** Matches values present in an iterable list.
* `df[~df["Country"].isin(["USA", "Sweden", "Brazil"])]` — **Inversion/NOT (`~`):** Negates the boolean Series to return values NOT in the list.

In [352]:
# Boolean indexing: filters and returns only the rows where the "Category" column equals "Electronics"
df[df["Category"] == "Electronics"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea

In [353]:
# Multi-condition boolean filtering: returns rows where both conditions are True using element-wise AND (&); parentheses are required around each condition
df[(df["Category"] == "Electronics") & (df["Country"] == "USA")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA

In [354]:
# Multi-condition boolean filtering: returns rows where at least one condition is True using element-wise OR (|); parentheses are required around each condition
df[(df["Category"] == "Electronics") | (df["Country"] == "USA")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea

In [355]:
# Comparison-based filtering: returns rows where the numeric value in "Quantity" is strictly greater than 5
df[df["Quantity"] > 5]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [356]:
# String filtering: returns rows where "CustomerName" starts with the letter "R" using the vectorized string accessor (.str)
df[df["CustomerName"].str.startswith("R")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India

In [357]:
# String filtering: returns rows where "CustomerName" ends with the lowercase letter "n" using the vectorized string accessor (.str)
df[df["CustomerName"].str.endswith("n")]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK

In [358]:
# Filters rows containing "john" anywhere in the text, ignoring case and skipping NaN values safely
df[df["CustomerName"].str.contains("john", case=False, na=False)]
# case=False: Ignores capitalization. Searching "john" will match "John", "JOHN", or "john". Default is case=True
# na=False: Crucial if your column has missing/null values (NaN). Without setting na=False, missing entries return NaN instead of False, which can raise an error when filtering

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [359]:
# Membership filtering: returns rows where "Country" matches any value present in the specified list using .isin()
df[df["Country"].isin(["USA", "Sweden", "Brazil"])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [360]:
# Inverted membership filtering: the tilde (~) negates the condition, returning rows where "Country" is NOT in the specified list
df[~df["Country"].isin(["USA", "Sweden", "Brazil"])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

# Modifying & Updating DataFrames Reference

### 1. Conditional Value Updating (`.loc`)
The syntax `df.loc[row_condition, "ColumnName"] = new_value` updates specific fields in-place without triggering chained assignment warnings:
* `df.loc[df["CustomerName"] == "Anna Ivanova", "Product"] = "Desk Pad"`  
  Finds matching rows and updates the target column value (e.g., changes `"Desk Clock"` to `"Desk Pad"`).
* `df.loc[df["Country"] == "USA", "Country"] = "United States"`  
  Replaces all matching entries across the column in-place.

---

### 2. Vectorized Column Transformation
* `df["Country"] = df["Country"].str.upper()`  
  Transforms all text values in the column to uppercase and overwrites the column in-place.

In [361]:
# Label-based boolean indexing: returns rows where "CustomerName" equals "Anna Ivanova" using .loc
df.loc[df["CustomerName"] == "Anna Ivanova"]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [362]:
# Conditional column update: changes "Product" from "Desk Clock" to "Desk Pad" where "CustomerName" is "Anna Ivanova"
df.loc[df["CustomerName"] == "Anna Ivanova", "Product"] = "Desk Pad"

# Filters and displays the updated row(s) for "Anna Ivanova" to verify the change
print(df.loc[df["CustomerName"] == "Anna Ivanova"])

    OrderID  CustomerName   Product   Category  Quantity  Price   OrderDate  \
39     1040  Anna Ivanova  Desk Pad  Furniture         1   35.0  2024-07-11

   Shipped  Country
39     Yes  Ukraine

In [363]:
# In-place value replacement: renames all occurrences of "USA" to "United States" in the "Country" column
df.loc[df["Country"] == "USA", "Country"] = "United States"

# Filters and displays all rows where "Country" is now "United States" to confirm the replacement
print(df.loc[df["Country"] == "United States"])

    OrderID   CustomerName         Product     Category  Quantity   Price  \
0      1001     John Smith          Laptop  Electronics         1  1200.0
17     1018  Michael Brown  Desk Organizer    Furniture         1    65.0
33     1034   Alex Johnson     Index Cards   Stationery       100     0.8

     OrderDate Shipped        Country
0   2024-06-01     Yes  United States
17  2024-06-19      No  United States
33  2024-07-05     Yes  United States

In [364]:
df["Country"] = df["Country"].str.upper()
print(df["Country"])

0     UNITED STATES
1            CANADA
2               UAE
3         SINGAPORE
4            MEXICO
5               UAE
6                UK
7       SOUTH KOREA
8             ITALY
9             JAPAN
10           FRANCE
11            INDIA
12        AUSTRALIA
13            SPAIN
14            CHINA
15            EGYPT
16           POLAND
17    UNITED STATES
18            JAPAN
19     SAUDI ARABIA
20           CANADA
21           BRAZIL
22          GERMANY
23         PAKISTAN
24           SWEDEN
25           FRANCE
26        ARGENTINA
27           RUSSIA
28      SOUTH KOREA
29            ITALY
30          MOROCCO
31          GERMANY
32         COLOMBIA
33    UNITED STATES
34            JAPAN
35               UK
36         PORTUGAL
37             IRAN
38      SOUTH KOREA
39          UKRAINE
Name: Country, dtype: str

# DataFrame Cleaning & Structural Modification Reference

### 1. Dropping Rows
* `df = df.drop(39)`  
  Removes the row with index label `39` and reassigns the resulting DataFrame.

---

### 2. Handling Missing Data (`NaN`)
* `df = df.dropna()`  
  Drops any row containing at least one missing value across columns and reassigns the cleaned DataFrame.
* `df.fillna({"OrderID": 0}, inplace=True)`  
  Replaces missing values in the `"OrderID"` column with `0` directly in memory without requiring variable reassignment.

---

### 3. Renaming Columns
* `df.rename(columns={"OrderID": "Order ID"}, inplace=True)`  
  Renames specified column labels using a dictionary map directly in memory.

In [365]:
# Row deletion: removes the row with index label 39 and reassigns the updated DataFrame
df = df.drop(39)

# Displays the last 5 rows to confirm index 39 is removed
print(df.tail())

    OrderID    CustomerName             Product     Category  Quantity  Price  \
34     1035   Yuki Yamamoto       Monitor Stand  Electronics         1   55.0
35     1036   Emma Thompson  Desk Lamp with USB    Furniture         1   68.0
36     1037   Carlos Santos    Wireless Earbuds  Electronics         1  125.0
37     1038  Leila Mansouri            Desk Pad    Furniture         1   28.0
38     1039      Daniel Kim         Power Strip  Electronics         2   18.0

     OrderDate Shipped      Country
34  2024-07-06     Yes        JAPAN
35  2024-07-07      No           UK
36  2024-07-08     Yes     PORTUGAL
37  2024-07-09     Yes         IRAN
38  2024-07-10      No  SOUTH KOREA

In [366]:
# Drops any row containing at least one NaN and reassigns the cleaned result back to df
df = df.dropna()

# Replaces NaN values in "OrderID" with 0 directly in memory without needing reassignment (returns None)
df.fillna({"OrderID": 0}, inplace=True)

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,UNITED STATES
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,POLAND
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,UNITED STATES
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,COLOMBIA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,UNITED STATES
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA

In [367]:
# Renames the column "OrderID" to "Order ID" directly in memory without needing reassignment
df.rename(columns={"OrderID": "Order ID"}, inplace=True)
print(df)

    Order ID      CustomerName                Product     Category  Quantity  \
0       1001        John Smith                 Laptop  Electronics         1
1       1002         Sarah Lee             Headphones  Electronics         2
2       1003          Ali Khan           Office Chair    Furniture         1
3       1004        Alice Wong              Desk Lamp    Furniture         3
4       1005     Carlos Mendez               Keyboard  Electronics         2
5       1006      Nora Ibrahim               Notebook   Stationery         5
6       1007       Emily Davis          Standing Desk    Furniture         1
7       1008        James Park                Monitor  Electronics         2
8       1009       Maria Rossi                    Pen   Stationery        10
9       1010  Takeshi Nakamura                  Mouse  Electronics         1
10      1011     Sophie Martin                 Webcam  Electronics         1
11      1012         Raj Patel           File Cabinet    Furniture         2
12      1013       Emma Wilson                Stapler   Stationery         3
13      1014   Diego Rodriguez              USB Drive  Electronics         5
14      1015         Lisa Chen              Bookshelf    Furniture         1
15      1016      Ahmed Hassan          Printer Paper   Stationery        20
16      1017     Anna Kowalski         Wireless Mouse  Electronics         2
17      1018     Michael Brown         Desk Organizer    Furniture         1
18      1019       Yuki Tanaka             Calculator  Electronics         1
19      1020   Fatima Al-Zahra             Whiteboard    Furniture         1
20      1021    David Thompson           Highlighters   Stationery         8
21      1022    Isabella Silva      Bluetooth Speaker  Electronics         1
22      1023    Oliver Schmidt           Office Plant    Furniture         2
23      1024        Zara Ahmed           Sticky Notes   Stationery        15
24      1025    Lucas Anderson           Tablet Stand  Electronics         1
25      1026      Chloe Dubois         Paper Shredder  Electronics         1
26      1027     Miguel Torres         Desk Chair Mat    Furniture         1
27      1028       Nina Petrov           Binder Clips   Stationery        12
28      1029      Seo-yeon Kim      Wireless Keyboard  Electronics         1
29      1030   Giuseppe Romano          Desk Calendar    Furniture         1
30      1031      Amira Hassan                USB Hub  Electronics         1
31      1032     Thomas Müller       Document Scanner  Electronics         1
32      1033   Sofia Rodriguez  Desk Drawer Organizer    Furniture         1
33      1034      Alex Johnson            Index Cards   Stationery       100
34      1035     Yuki Yamamoto          Monitor Stand  Electronics         1
35      1036     Emma Thompson     Desk Lamp with USB    Furniture         1
36      1037     Carlos Santos       Wireless Earbuds  Electronics         1
37      1038    Leila Mansouri               Desk Pad    Furniture         1
38      1039        Daniel Kim            Power Strip  Electronics         2

     Price   OrderDate Shipped        Country
0   1200.0  2024-06-01     Yes  UNITED STATES
1    150.0  2024-06-03      No         CANADA
2    300.0  2024-06-04     Yes            UAE
3     45.0  2024-06-05     Yes      SINGAPORE
4     80.0  2024-06-06      No         MEXICO
5      5.0  2024-06-07     Yes            UAE
6    450.0  2024-06-08     Yes             UK
7    220.0  2024-06-09      No    SOUTH KOREA
8      1.5  2024-06-10     Yes          ITALY
9     35.0  2024-06-11     Yes          JAPAN
10    85.0  2024-06-12     Yes         FRANCE
11   180.0  2024-06-13      No          INDIA
12    12.0  2024-06-14     Yes      AUSTRALIA
13    25.0  2024-06-15     Yes          SPAIN
14   280.0  2024-06-16      No          CHINA
15     8.0  2024-06-17     Yes          EGYPT
16    45.0  2024-06-18     Yes         POLAND
17    65.0  2024-06-19      No  UNITED STATES
18    15.0  2024-06-20     Yes          JAPAN
19   120.0  2024-06-21     Yes   SAUDI ARABIA
20     3.5  2024-06-22      No         CANADA
21    95.0  2024-06-23     Yes         BRAZIL
22    35.0  2024-06-24     Yes        GERMANY
23     4.0  2024-06-25      No       PAKISTAN
24    28.0  2024-06-26     Yes         SWEDEN
25    75.0  2024-06-27     Yes         FRANCE
26    22.0  2024-06-28      No      ARGENTINA
27     2.5  2024-06-29     Yes         RUSSIA
28   110.0  2024-06-30     Yes    SOUTH KOREA
29    18.0  2024-07-01      No          ITALY
30    32.0  2024-07-02     Yes        MOROCCO
31   140.0  2024-07-03     Yes        GERMANY
32    42.0  2024-07-04      No       COLOMBIA
33     0.8  2024-07-05     Yes  UNITED STATES
34    55.0  2024-07-06     Yes          JAPAN
35    68.0  2024-07-07      No             UK
36   125.0  2024-07-08     Yes       PORTUGAL
37    28.0  2024-07-09     Yes           IRAN
38    18.0  2024-07-10      No    SOUTH KOREA

# Sorting & Export Reference

### 1. In-Place Sorting
* `df.sort_values("Price", ascending=False, inplace=True)`  
  Sorts the DataFrame by `"Price"` in descending order (highest to lowest) directly in memory without reassignment.

---

### 2. Exporting to CSV
* `df.to_csv("orders_modified.csv", index=False)`  
  Exports the DataFrame to a CSV file named `"orders_modified.csv"`, omitting the default integer row index to prevent extra unnamed columns upon re-reading.

In [368]:
# Sorting rows: sorts the DataFrame by "Price" in descending order (highest to lowest)
df.sort_values("Price", ascending=False, inplace=True)

In [ ]:
# File export: saves the DataFrame to a CSV file named "orders_modified.csv" without writing row index numbers
df.to_csv("orders_modified.csv", index = False)